name: LearningFun
description: A sample Polymer application
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  polymer: any
  paper_elements: any
  route_hierarchical: any
  smartcanvas:
    path: ../../smartcanvas
transformers:
- polymer:
    entry_points: web/index.html
- $dart2js:
    minify: false
