name: canvas_lib
version: 0.0.1
authors: [Kun Zhao <kzhdev@gmail.com>]
description: svg/html5_canvas playground

environment:
  sdk: '>=1.0.0 <=2.0.1'

dependencies:
  dart_ext: "^1.0.0"
  r2d2: ">=0.1.1 <0.2.0"

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc