name: playground
description: A web app that uses AngularDart Components
version: 0.0.1

environment:
  sdk: '>=1.24.0 <=2.0.1'

dependencies:
  jsproxy: "^1.0.0"
  canvas_lib:
    path: ../canvas_lib

dev_dependencies:
  browser: "^0.10.0+2"
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- dart_to_js_script_rewriter

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
